# Note: It is important to make sure you include the <bsd.kmod.mk> makefile after declaring the KMOD and SRCS variables.

KMOD    =  trng
SRCS    =  trng.c

#CFLAGS  += -DDEBUG -g

.include <bsd.kmod.mk>
